services:
  redis:
    container_name: nashvillest-redis
    image: redis:alpine
  hubot:
    container_name: nashvillest-hubot
    build: .
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://nashvillest-redis:16379
    depends_on:
      - redis
